export const products = [
  {
    id: 0,
    title: "Nordic Chair",
    image: "product-1",
    price: 50,
    name: "chair",
    category: "furniture",
  },
  {
    id: 1,
    title: "Kruzo Aero Chair",
    image: "product-2",
    price: 400,
    name: "chair",
    category: "furniture",
  },
  {
    id: 2,
    title: "Ergonomic Chair",
    image: "product-3",
    price: 110,
    name: "chair",
    category: "furniture",
  },
  {
    id: 3,
    title: "Hot Dog with Chease",
    image: "bowl-2",
    price: 110,
    name: "pizza",
    category: "food",
  },
  {
    id: 4,
    title: "Ergonomic Chair",
    image: "product-3",
    price: 550,
    name: "chair",
    category: "furniture",
  },
  {
    id: 5,
    title: "Kruzo Aero Chair",
    image: "product-2",
    price: 400,
    name: "chair",
    category: "furniture",
  },
  {
    id: 6,
    title: "Ergonomic Chair",
    image: "product-1",
    price: 350,
    name: "chair",
    category: "furniture",
  },
  {
    id: 7,
    title: "Vegitables with Chease",
    image: "bowl-3",
    price: 110,
    name: "pizza",
    category: "spice products",
  },
  {
    id: 8,
    title: "Vivo v7",
    image: "phone-1",
    price: 1010,
    name: "phone",
    category: "digital product",
  },
];
