"use client";
/* eslint-disable @next/next/no-css-tags */

import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import { Providers } from "@/lib/redux/Providers";
import { Inter } from "next/font/google";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title:
    "Furniture React Redux Bootstrap 5 Template for Furniture and Interior Design Websites by RH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="keywords" content="furniture , table , chair" />

        <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="/assets/css/style.css" />
      </head>
      <Providers>
        <body className={inter.className}>
          <Header />
          {children}
          <ProgressBar
            height="2px"
            color="white"
            options={{ showSpinner: false }}
            shallowRouting
          />
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
